name: Deploy to Render

on:
  push:
    branches:
      - main # Change this if you want to deploy from a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          docker build -t ghcr.io/${{ secrets.GITHUB_REPOSITORY }}:${{ github.sha }} .
          echo $RENDER_API_KEY | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ secrets.GITHUB_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
