name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Glitch
        run: |
          git clone https://github.com/${{ github.repository }} glitch-app
          cd glitch-app
          echo "FROM ghcr.io/${{ github.repository }}:latest" > Dockerfile
          git add Dockerfile
          git commit -m "Deploy to Glitch"
          git remote add glitch https://glitch.com/edit/#!/placid-judicious-rock
          git push glitch main:master --force
